### PR TITLE
Add retrieve robots.txt SubdomainDataExtractor

### PR DESCRIPTION
**Pull request by romainr88**
Add retrieve robots.txt and CrossDomain.xml in SubdomainDataExtractor

### CODE REVIEW

**Comment by eranzim** [comment]
1. No need to print anything if they don't exist (best effort, as is most of this script)
2. No need for -r (recursive) when getting a single file with wget
3. Since there may be different robots.txt, etc. for different subdomains / protocols, you should move this logic inside the main loop, possibly to the already-long code lines of wget -r.. (Is it possible to download multiple targets with a single wget?). The downloaded files should be saved to the same location as the entire website (e.g. "$dir_name/websites/$subdomain/80", etc.)

**Comment by romainr88** [comment]
1. Ok, i'll correct it
2. That's right, i didn't paid attention about that
3. I've started to do it into the main loop, but i have noticed the two "wget" for 80 and 443 already retrieve the files into "$dir_name/websites/$subdomain/80" and "$dir_name/websites/$subdomain/443". that's why i put it outside the main loop actually. I've tried for "adobe.com" if you want to try.
I think you can get multiple files with "wget -i" on one URL.

**Comment by eranzim** [comment]
You're right about robots.txt being downloaded on www.adobe.com and also www.facebook.com, but it doesn't seem consistent - for example, it isn't downloaded for www.pizzahut.co.il, even though it exists. Also, crossdomain.xml seems like it's never downloaded, even when it exists.

wget -i might work, so might wget -I (capital i) if I understood the documentation correctly, without requiring an additional input file.

**Comment by romainr88** [comment]
I've updated the file, so it's work with www.pizzahut.co.il, i don't have actually find more others proper ways. I've changed the way to check the URLs because this website return me status "301" instead "200".

Maybe check the files if them exists in folders "$dir_name/websites/$subdomain/80" and "$dir_name/websites/$subdomain/443" can be a good idea if them already downloaded by the wget for 80 and 443 no ?

wget -i need list, so i don't think it's worth it to make a temp file for 2 URLs and delete it after. For wget -I it's seems works only on directory like this "wget -r --include-directories="/folders/folder" http://www.adobe.com/folders/"

**Comment by eranzim** [comment]
Checking if the files were downloaded (if they exist in the local directory) could work.
No need to check if they exist on the server before wget-ing them - if they don't, the wget will simply fail silently (because of -q).
Actually, I checked (please verify me), and it seems that if robots.txt already exists, then it's replaced by the one from the server (assuming you pass the -r flag - whether for a whole website or for a single file). If this is indeed the case, I think you should just wget those files regardless of if they were auto-downloaded (best effort), into the correct dirs. Either before or after the other downloads.
I would move the mkdirs out of the long lines (do them synchronously beforehand), and then the new wgets could also be in parallel (with & at the end).

**Comment by romainr88** [comment]
Yes you're right, if robots.txt already exists with only "wget" it do a copy of the file robots.txt.1 otherwise with "wget -r" it's overwrite the robots.txt

What do you think about this way for making folders and downloading datas/files : 
https://gist.github.com/romainr88/e3c17308f6208512a05d29a317654b77
The first loop and first array can be replaced by 2 variables for each protocols too

I've use "wget -r" on the second "wget" for overwriting the files instead check if the files exists

**Comment by eranzim** [comment]
Looks almost good :)
A few things to correct:
1. No need for if-else, the loop takes care of that for you (you have the same code twice).
2. Since I want things to run fast (in parallel whenever possible), I want to separate the mkdirs (make them synchronous), and then do the 2 long lines with a & at the end.
Something like this:
mkdir subdomain
for protocol:
    wget website && find comments &
    for file:
        wget file &

**Comment by romainr88** [comment]
Sorry for late answer, i was busy recently
1. Ok, i don't know if you wanted to do a test for protocol
2. I've update the file : https://gist.github.com/romainr88/e3c17308f6208512a05d29a317654b77
It's make first all actions for the protocol 80 and then all actions for the protocol 443

**Comment by eranzim** [comment]
Looks good - just add a & at the end of both wget lines so that they run in the background (in parallel), and I think we can merge it in :)

**Comment by romainr88** [comment]
Oops yes i forgot the "&" ^^
I've update extractor.sh with the new code :)

**Comment by eranzim** [comment]
Good job! Thanks for your help! :)

**Pull request merged**
